### ISSUE TITLE
Load test batch-file-ingest sample with volume services on PCF

### ISSUE THREAD

**Issue by sabbyanandan** [spring-cloud/spring-cloud-dataflow-samples#75]
As a developer, I'd like to load test the [file-ingest sample](https://docs.spring.io/spring-cloud-dataflow-samples/docs/current/reference/htmlsingle/#_using_the_cloud_foundry_server_2) with large files of size >2G or more each. 

child of spring-cloud/spring-cloud-dataflow-samples#66

**Comment by chrisjs** [comment]
rather than add extra network overhead d/ling a file from somewhere, i deployed an application that was bound to the NFS service, SSH'ed into the application container and used `dd` to create a ~3GB file on the target mount dir. network configuration and so on would likely play a factor in the below stats, one would likely optimize for NFS. the result of this test is:

```
3252952+0 records in
3252952+0 records out
3331022848 bytes (3.3 GB) copied, 1267.14 s, 2.6 MB/s

real	21m7.141s
user	0m8.240s
sys	1m2.672s
```
